### ISSUE TITLE
Critical Bug: wrapper.captureEvent nor wrapper.triggerEvent DO NOT work 

### ISSUE THREAD

**Issue by jnevo-fcms** [TagCommander/vue-tag-commander#20]
**Impossible to trigger an event using captureEvent nor triggerEvent methods.**

In the last version 1.1.0, the following instruction is made in the constructor of `TC_Wrapper` class:
https://github.com/TagCommander/vue-tag-commander/blob/df2434b562943f0e4010a591e4acbdf074f26e85/src/index.js#L6

The problem is that the method `triggerEvent` doesn't exist in the class. There is stil the method `captureEvent` https://github.com/TagCommander/vue-tag-commander/blob/c5b048a279b388c27633cc83eecabeab5d25d4c3/src/index.js#L190
 So instead of introducing the backward compatibility, this line breaks `captureEvent` since it makes `wrapper.captureEvent` `undefined`

**I guess the developer has completely forgotten to rename the method `captureEvent` into `triggerEvent`.**

**Comment by RomainLK** [comment]
Oops, sorry for the inconvenience. We have just pushed a fixed version, 1.1.1 to npm in order to rename that function as told in the documentation.

https://github.com/TagCommander/vue-tag-commander/releases/tag/v1.1.1
