### ISSUE TITLE
CommonJS module

### ISSUE THREAD

**Issue by mtancoigne** [TagCommander/vue-tag-commander#28]
Hello,

We are integrating this plugin in our application and have issues with Jest when it comes to test components: the module is only available in ECMAScript, and Jest likes CommonJS.

Although there is an experimental way to use Jest with ECMAScript, we prefer to avoid it, as it would change the whole configuration. 

Is it possible or do you plan to provide a CommonJS version of this module in the future releases?

**Comment by RomainLK** [comment]
Hello

concerning your issue, I'm making a UMD module which should work with your Jest setup as a CJS module, though it's taking a bit more effort than I expected. In the mean time I have a question for your environment. In my latest output, I have a transpilation to ES5 which result in the need of including Babel' regenerator. Is it an issue for you and in that case, would a ES2017 code be preferable?

**Comment by RomainLK** [comment]
I gave up on Babel/Gulpand now have a CommonJS build. I have published version 1.3.0

The CommonJS package can be  imported  with `require("vue-tag-commander/cjs")`

**Comment by mtancoigne** [comment]
Excellent, i'll check with the team if it's ok for them.
